# AMATH Scientific Computing
## Quiz 1
### Date: 7th Oct 2022
Attempt 1

In [1]:
import numpy

Q1. Which of the following commands creates a matrix of zeros with 10 rows and 7 columns? (Select all that apply).

In [4]:
A = numpy.zeros(10, 7)
A

TypeError: Cannot interpret '7' as a data type

In [6]:
A = numpy.zeros([10, 7])
A

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [7]:
A = numpy.zeros(10)
A

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
A = numpy.zeros
A

<function numpy.zeros>

In [11]:
A = numpy.zeros([7,10])
A

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
A = 0*numpy.ones([10, 7])
A

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [13]:
A = 0*[10, 7]
A

[]

Q2. Which of the following commands creates a vector of 10 elements without typing each term?

In [14]:
vec = numpy.arange(0, 10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
vec = numpy.array([1, 10])
vec

array([ 1, 10])

In [17]:
vec = numpy.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
vec

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
vec = numpy.array([0, 10])
vec

array([ 0, 10])

In [19]:
vec = numpy.arange(10)
vec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
vec = numpy.arange(0, 20, 2)
vec

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
vec = numpy.arange(1, 10)
vec

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
vec := numpy.arange(0, 10)
vec

SyntaxError: invalid syntax (2099887285.py, line 1)

Q3. Consider the following block of code

In [24]:
x = numpy.arange(5)
if x[-3]==3:
     print(x[x])

In [25]:
x = numpy.arange(5)
if x[-3]==3:
     print([x])

In [35]:
x = numpy.arange(5)
print(x)
print(x[-3])
if x[-3]==2:
     print(x[x])

[0 1 2 3 4]
2
[0 1 2 3 4]


Q4. What is the output (printed to screen) of the following code:

In [30]:
x = numpy.zeros(100)
x[0] = 0; x[1] = 1
for i in range(2, 100):
     x[i] = x[i-1] + x[i-2];
     if x[i] > 50:
          print(x[6])
          break

8.0
